### ISSUE TITLE
Downloads down from rdf-ext.bergnet.org

### ISSUE THREAD

**Issue by jmvanel** [rdf-ext/rdf-ext-dist-builder#12]
This used to work until a few days ago :
https://rdf-ext.bergnet.org/dist/rdf-ext-all-1.0.0.src.js

Apparently, according to
https://github.com/rdf-ext/rdf-ext-dist-builder#import-into-browser
this should work today:
http://rdf-ext.bergnet.org/dist/rdf-ext-all-latest.js
but this URL says 
`Cannot GET /dist/rdf-ext-all-latest.js`

**Comment by bergos** [comment]
Sorry, accidentally broke the docker config. Fixed it, should work again.
