### ISSUE TITLE
[SOLVED] Browser version RDF-ext

### ISSUE THREAD

**Issue by nicky508** [rdf-ext/rdf-ext-dist-builder#3]
Missing the possibility to create or use a browser version of RDF-EXT.  The instruction  (src=js/rdf-ext.js) doesn`t work, since the browser fails on the "require" statements.

**Comment by ktk** [comment]
On what file was that? The pre-built one or one you selected? If you selected it, what checkboxes did you tick?

**Comment by bergos** [comment]
@nicky508 The distribution attaches all the classes to the window object. [This file](https://github.com/bergos/rdf-ext-dist-builder/blob/master/modules.json) contains the property to module mapping. For example, if you want to parse a Turtle file call:

```
window.N3Parser.parse(turtleString).then(function(graph) {})
```

or just

```
N3Parser.parse(turtleString).then(function(graph) {})
```

`require` is only available if you use browserify to build to your project.

**Comment by bergos** [comment]
I created another [issue](https://github.com/rdf-ext/rdf-ext-dist-builder/issues/5), because I'm not sure if we should put all that stuff in the global context.

**Comment by nicky508** [comment]
@ktk Ok, so I discovered that it does not matter whether you use the distribution builder or just use the latest version of rdf-ext (http://rdf-ext.bergnet.org/dist/rdf-ext-all-latest.js).  When included as a normal js script, the browser drops this error: "TypeError: require(...) is not a function". 

@bergos Yes, I see but the require statements are standard in the js files.

**Comment by bergos** [comment]
@nicky508 It's a problem of the SimpleRDF library. Soon this library will get an update. In the meantime can build a custom version without SimpleRDF (RDF as easy as js objects). Than it should work.

**Comment by semanticfire** [comment]
Is that a specific version you build for us, or can we build it ourselves from the web interface if we omit the SimpleRDF library ?

**Comment by bergos** [comment]
You can build it with the web interface. I will try to fix the problem today or tomorrow and will publish a new distribution.

**Comment by bergos** [comment]
I published a new version of SimpleRDF, updated the dependencies and also updated the pre-built distributions.

**Comment by nicky508** [comment]
Yes it works...
Used the prebuilt version (http://rdf-ext.bergnet.org/dist/rdf-ext-all-latest.js) on my test script and it worked.

Thanks, keep up the good work.
